### ISSUE TITLE
issue installing php55

### ISSUE THREAD

**Issue by vgross** [Homebrew/homebrew-php#1530]
I have an issue when I try to install php55. I've tried to remove the entire folder instantclient and I don't have the symlink of "ldap.h" in "/usr/local/include" but it still the same. I have been trying to fix that for 3h as now I'm totally confused, so I need help.

<problem description>

Parameter | Value
------------------ | ------------------
**OS X Version:** | 10.10.2 (14C109)
**Homebrew Version:** | Homebrew 0.9.5
**PHP Version in use:** | I try to have one !
**Xcode Version:** | 6.1.1 (6A2008a)
**Output of gcc -v:** | Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
**Output of php -v:** | PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
**Output of brew install -v path/to/homebrew-php/the-formula-you-want-to-test.rb --with-your --opts-here within a gist** | https://gist.github.com/vgross/9b5ea48b197e35374cb0
**Output of brew doctor within a gist** | https://gist.github.com/vgross/b123241eaa7513c0b082

Thanks

**Comment by trokotech** [comment]
Hi,
I fixed it following this:

https://techblog.willshouse.com/2013/11/20/hombrew-upgrade-php54-make-extldapldap-lo-error-1/

**Comment by vgross** [comment]
Yes everyone could fix this issue with this way, I've already found this blog during my research. Unfortunately, this symlink, is not present in my system and I don't have a clue why I still have this issue...

**Comment by vgross** [comment]
I have follow this instruction in order to install instantclient of oracle: http://www.enavigo.com/2012/01/04/enabling-oracle-oci8-php-extension-on-os-x-snow-leopard/ 

Maybe that could help someone to try to fix my issue... I'm desperate ! I think that I will use my time capsule to get an older image of my system

**Comment by vgross** [comment]
I found how to fix that by doing exactly the opposite process of the link that I've just mentioned to install oci8 driver.

I've deleted all the copied files (except ldap.h in /usr/include) and I could compile PHP.
