### ISSUE TITLE
Issue with php 5.3 on Sierra (php.dSYM)

### ISSUE THREAD

**Issue by yvh** [Homebrew/homebrew-php#3634]
## Description

(Unfortunately) I need php 5.3 on macOS Sierra.
After install the binary is /usr/local/bin/php.dSYM and not /usr/local/bin/php (same for php-cgi)

I think that we must to change the multi-sapi-5.3.29-homebrew.patch with the correct darwin kernel version.
 => *darwin9*|*darwin10*|*darwin11*|*darwin12*|*darwin13*|*darwin14*

and add *darwin16* (and *darwin15* may be ?)

It's correct ?

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12
**Homebrew Version:**   | 1.0.5
**PHP Version in use:** | 5.6.24

**Output of gcc -v:**
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output of php -v:**
PHP 5.6.24 (cli) (built: Aug  8 2016 16:58:37) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by yvh** [comment]
Ok it's already on the pipe.

See pull request #3621

**Comment by javian** [comment]
@yvh We need help to pull this off since I can't manage the complexity of the patch at the moment. I tried  to put in the changes you suggested and it seems that darwin15 got lost when freetype changed their code structure. We have also considered to move the older php versions that are no longer supported upstream out of this tap and place them elsewhere since it will only become harder to support this as time goes by.

**Comment by yvh** [comment]
@javian I have make a test with your patch file but with my modifications. 
Here the gist : https://gist.github.com/yvh/08b306fc722fbc31c446f794567dfa66

Do you want I create a pull request directly or you modify the code ?

Please don't deprecate the 5.3 version :-)

**Comment by javian** [comment]
@yvh I merged the updated bottle yesterday, can you confirm that it works ?

**Comment by yvh** [comment]
@javian Yep it works ;-) Thanks

**Comment by clintonpaquin** [comment]
Installed today and still seeing this issue.  Anything I need to do to get the binary pulled in?

````
/usr/local/Cellar/php53/5.3.29_8/bin > ll
total 20184
drwxr-xr-x   8 cpaquin  admin       256 Nov 21 18:12 .
drwxr-xr-x  15 cpaquin  admin       480 Nov 21 17:53 ..
lrwxr-xr-x   1 cpaquin  admin         9 Nov 21 17:53 phar -> phar.phar
-rwxr-xr-x   1 cpaquin  admin     14855 Nov 21 17:53 phar.phar
-rwxr-xr-x   1 cpaquin  admin  10298124 Nov 21 17:52 php-cgi.dSYM
-rwxr-xr-x   1 cpaquin  admin      4501 Nov 21 17:53 php-config
-rwxr-xr-x   1 cpaquin  admin         0 Nov 21 18:00 php.dSYM
-rwxr-xr-x   1 cpaquin  admin      4541 Nov 21 17:53 phpize
```

**Comment by higidi** [comment]
Same here :-(
