### ISSUE TITLE
Getting php71-imagick error

### ISSUE THREAD

**Issue by jajajaime** [Homebrew/homebrew-php#3842]
## Description

PHP scripts on the CLI output an error with loading php71-imagick.
Brew is updated and upgraded.
The error is on the `php-v` section.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.1
**Homebrew Version:**   | 1.1.2
**PHP Version in use:** | 7.1.0
**Xcode Version:**      | 8.1.0.0.1.1476494586

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 7.1.0 (cli) (built: Dec 11 2016 22:53:08) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

**Comment by javian** [comment]
This might be related to an imagick update. Can you try and do `brew reinstall -s php71-imagick` and see if the problem persists ?

**Comment by alcaeus** [comment]
@javian I encountered the same problem yesterday when updating a couple of machines from php70 to php71. Running with `-s` fixed the issue.

**Comment by jajajaime** [comment]
That did it. Thanks for the quick response. You can close this.

**Comment by javian** [comment]
Glad to see that it fixed it! Could someone submit a revision bump of the imagick formulas ? This would solve the issue for everyone once its been merged.

**Comment by brtdv** [comment]
I'm having this same issue with PHP 7.0
I'm running macOS 10.12.1 

```
☁  ~  php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 7.0.14 (cli) (built: Dec  9 2016 07:34:25) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

When I reinstall from source with `brew reinstall -s php70 php70-imagick`, I'm getting this warning:

```
☁  ~  php -v
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1686 but version 1578241 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

Warning: Version warning: Imagick was compiled against Image Magick version 1686 but version 1578241 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
PHP 7.0.14 (cli) (built: Dec 13 2016 09:55:09) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

What else would I need to reinstall to make the Version warning disappear? 


This is my `brew doctor` output

```
☁  ~  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libbeidpkcs11.4.1.19.dylib
````

**Comment by apfelbox** [comment]
I got the same error for `php70-imagick`, always got 

```
▲ php -v
Xdebug requires Zend Engine API version 220131226.
The Zend Engine API version 320151012 which is installed, is newer.
Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 7.0.14 (cli) (built: Dec 12 2016 20:20:09) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

Reinstallation with `brew reinstall -s php70-imagick` fixed it for me, I got no build warnings, it installed cleanly and now everything is running smoothly again.

👍

**Comment by javian** [comment]
This has now been fixed by merging #3858

**Comment by John-ZAF** [comment]
Greetings all, 

I know this was closed, but after a lot of searching this is the closest post I can find relating to the issue I am having...

home-brew is clean, upgraded, pruned and is at version
Homebrew 1.1.7
Homebrew/homebrew-core (git revision 8c01; last commit 2017-01-14)
php56-imagick: 3.3.0_6
imagemagick: 7.0.4-4

env is simple Home-brew Apache 2.4 with multiple php versions (55,56,70,71) NB: all versions with INTL extensions work as per normal...

$ brew reinstall php56 php56-intl **php56-imagick** is giving me some issues (first ever) - actually it is just the latter **imagick** - everything else is as it always is. The installation goes through seamlessly and afterwards php -v brings up the errors and the image magic extension is not loaded. It would appear that PHP is looking for an older version of imagemagick....

`
Johns-MacBook-Pro:Formula johnlaatz$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/**libMagickWand-6.Q16.3.dylib**
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/**libMagickWand-6.Q16.3.dylib**
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 5.6.29 (cli) (built: Jan 15 2017 13:41:38) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
`

Installed file = /usr/local/Cellar/imagemagick/7.0.4-4/lib/libMagickWand-7.Q16HDRI.dylib

It may or may not be worth noting that building from source fails.

`/private/tmp/php56-imagick-20170115-32311-8ljahu/imagick-3.3.0/imagick_class.c:6488:65: error: too few arguments to function call, expected 4, have 3
        status = MagickGetImageGreenPrimary(intern->magick_wand, &x, &y);
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~                            ^
/usr/local/Cellar/imagemagick/7.0.4-4/include/ImageMagick-7/MagickWand/magick-image.h:80:1: note: 'MagickGetImageGreenPrimary' declared here
extern WandExport MagickBooleanType
^
/private/tmp/php56-imagick-20170115-32311-8ljahu/imagick-3.3.0/imagick_class.c:6776:63: error: too few arguments to function call, expected 4, have 3
        status = MagickGetImageRedPrimary(intern->magick_wand, &x, &y);
                 ~~~~~~~~~~~~~~~~~~~~~~~~                            ^
/usr/local/Cellar/imagemagick/7.0.4-4/include/ImageMagick-7/MagickWand/magick-image.h:80:1: note: 'MagickGetImageRedPrimary' declared here
extern WandExport MagickBooleanType
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [imagick_class.lo] Error 1
`

Any ideas would be very much appreciated?

**Comment by javian** [comment]
@John-ZAF php56-imagick needs to be updated to the latest version which is on the way.

**Comment by John-ZAF** [comment]
Thanks, standing by

P.S. brew reinstall php70 php70-intl php70-imagick has the same issues… php70 and intl install perfectly but imagick fails. I presume for the same reason…

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0

**Comment by jimmiw** [comment]
I did a 
brew reinstall -s php70-imagick
and it worked for me.

**Comment by John-ZAF** [comment]
Great, thanks Jimmi, worked for me too!

Johns-MacBook-Pro:~ johnlaatz$ php -i | grep "imagick"
Additional .ini files parsed => /usr/local/etc/php/7.0/conf.d/ext-imagick.ini,
imagick
imagick module => enabled
imagick module version => 3.4.2
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
imagick.locale_fix => 0 => 0
imagick.progress_monitor => 0 => 0
imagick.skip_version_check => 0 => 0
Johns-MacBook-Pro:~ johnlaatz$

**Comment by jimmiw** [comment]
As a side note, I had to downgrade imagemagick to 6.x instead of 7.x, else I kept getting exceptions about a lib not being found

**Comment by BorisAnthony** [comment]
I'm having this issue with php56…
@javian has that update happened? where can I look to see? thanks!
@jimmiw did you downgrade via brew? how? than you too :)

**Comment by John-ZAF** [comment]
Have you run brew update? I recently got the latest php56 and it all installed smoothly.

(Sent from my mobile, please excuse any resulting brevity)

**Comment by DavidLambauer** [comment]
I still have problems with Imagick. Every php call is leading to the following warning:

`Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php70-imagick/imagick.so' - dlopen(/usr/local/opt/php70-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.1.dylib
  Referenced from: /usr/local/opt/php70-imagick/imagick.so
  Reason: image not found in Unknown on line 0`

I followed the instructions and tipps of this thread, reinstalled php70 completly but still run into the error above.

Can someone assist?

**Comment by alcaeus** [comment]
See https://github.com/Homebrew/homebrew-php/issues/3916#issuecomment-276072774. The key is to `brew reinstall -s php70-imagick` to recompile from source.

**Comment by DavidLambauer** [comment]
That doesn't work for me atm. When I run `/usr/local/bin/php -v`, I am getting the following:

`PHP 7.1.1 (cli) (built: Jan 21 2017 13:36:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies`

But the error is still the 7.0 one. How can that be?

**Comment by alcaeus** [comment]
If you're getting php70 errors even though you're running, best create a new issue with the relevant information. Something seems fishy 🐟

**Comment by huebs** [comment]
@DavidLambauer that happened to me because I have both php70 and php71 installed. Here's how I fixed it:

```bash
# Unlink php71
brew unlink php71 php71-apcu
# Link php70
brew link php70 php70-apcu
# Reinstall Imagick Extension
brew reinstall -s php70-imagick
```

**Comment by DavidLambauer** [comment]
Thanks @huebs , I decided to reinstall everything around. My issue seems to be very fishy so it must have been a local thing... Works on my mashine at the moment with PHP 7.1.1! 😝

**Comment by BorisAnthony** [comment]
It seems to be different between php56 and php7x.

"brew reinstall -s" doesn't fix the issue for php56 (I dumped and reinstalled everything and still get:

`Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.1.dylib
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-magickwand/magickwand.so' - dlopen(/usr/local/opt/php56-magickwand/magickwand.so, 9): Library not loaded: /usr/local/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php56-magickwand/magickwand.so
  Reason: image not found in Unknown on line 0`

Question: has php56-imagick been updated (it was mentioned to be "on the way", above, 15 days ago)?

**Comment by BorisAnthony** [comment]
I would try if I knew how… 

But really, this shouldn’t happen, right? I though Homebrew checks dependencies etc? Really frustrating. :\

**Comment by jimmiw** [comment]
brew info imagemagick <-- shows current version
brew search imagemagick <-- shows available packages
brew remove imagemagick
brew install imagemagick@6

Then it should install the older imagemagick version.

About brew checking for dependencies? yes... but it up to us as uses, to destroy that... :)

**Comment by alcaeus** [comment]
@BorisAnthony unfortunately, every update to the imagemagick formula requires a revision bump of php*-imagick to generate new bottles. However, running an install from source (using `-s`) should always work. Did you run `brew upgrade` before?

**Comment by BorisAnthony** [comment]
@jimmiw thank you. I tried installing @6 but didn't seem to work out. Will try again. Sometime. Already lost 2 Sundays trying to fix this. And yes, I am sure I destroyed alot in my frantic trying to fix it. :) So many yaks, so little time.

@alcaeus "As a user, I should not have to care about production issues" ;) `brew upgrade` is what broke my perfectly working setup. And yes, i run it regularly, despite the trauma ;)

**Comment by alcaeus** [comment]
@BorisAnthony I agree - unfortunately this is a problem that reappears if you run `brew upgrade` between an update to the `imagemagick` formula and a rebuild of the `php*-imagick` bottles.

To clear up any possible confusion regarding `imagemagick@6`, this formula is only needed for `php53-imagick`. All other formulae require `imagemagick` version 7 and build against it.

**Comment by jajajaime** [comment]
This happened to me again today.
```
$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.0.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.0.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 7.1.8 (cli) (built: Aug  7 2017 18:39:48) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

Installing from source fixes it like always, but still annoying.

**Comment by alcaeus** [comment]
@jajajaime I've created a pull request to bump revisions. Fixes it like always, but still annoying 😂

**Comment by robrecord** [comment]
Happening for me today using php71 and php71-imagick. How can this be avoided in future?

**Comment by alcaeus** [comment]
@robrecord technically, not at all. What's strange is that I'm not getting the error after upgrading imagemagick. Did you install PHP today or was it installed previously and you only upgraded imagemagick?

**Comment by evictor** [comment]
This worked for me, but out of curiosity, what does `-s` flag do? Couldn't find it in docs.

**Comment by alcaeus** [comment]
`-s` toggles a build from source instead of using a precompiled bottle, thus ensuring that the binary is compiled against the imagemagick version on your system. That's why a revision bump to all imagemagick-dependent formulae always fixes this.
