### ISSUE TITLE
PHP Warning:  Module 'XXX' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by bocharsky-bw** [Homebrew/homebrew-php#3896]
## Description

Due to the latest upgrade with `brew upgrade` command, I started to get weird PHP warnings - see logs below

## Context and Logs
```
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'yaml' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'OAuth' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'yaml' already loaded in Unknown on line 0
```

Parameter | Value
--------- | ------------------
**OS X Version:**       | MacOS Sierra 10.12.2
**Homebrew Version:**   | Homebrew 1.1.6-9-g98dadd907, Homebrew/homebrew-core (git revision e6bc; last commit 2017-01-04)
**PHP Version in use:** | PHP 7.1.0 (cli) (built: Dec  2 2016 11:32:42) ( NTS )
**Xcode Version:**      | Version 8.2.1 (8C1002)

**Output of gcc -v:**
```
onfigured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**
```
PHP 7.1.0 (cli) (built: Dec  2 2016 11:32:42) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

I don't understand why PHP trying to load these extensions one more time? Probably the new version of brew has some misconfiguration. Uninstalling and reinstalling php71 with its extensions doesn't help.

**Comment by javian** [comment]
What does `php --ini` tell you ? Does it give any clues as to why this could happen ?

**Comment by Gadgetdude** [comment]
I'm having a similar issue, but with PHP 5.6. So we can probably rule out that it has something to do with a specific PHP version. Maybe a recent update on brew itself? I've already checked the php.ini file but nothing is added double there.

When I run `php -i` (optional with ` | grep .ini` added) I get this. I'm not sure if it just shows what was in the `conf.d` folder or that it includes all the files both ways.
```
Scan this dir for additional .ini files => /usr/local/etc/php/5.6/conf.d
Additional .ini files parsed => /usr/local/etc/php/5.6/conf.d/ext-amqp.ini,
/usr/local/etc/php/5.6/conf.d/ext-apcu.ini,
/usr/local/etc/php/5.6/conf.d/ext-igbinary.ini,
/usr/local/etc/php/5.6/conf.d/ext-imagick.ini,
/usr/local/etc/php/5.6/conf.d/ext-intl.ini,
/usr/local/etc/php/5.6/conf.d/ext-mcrypt.ini,
/usr/local/etc/php/5.6/conf.d/ext-memcached.ini,
/usr/local/etc/php/5.6/conf.d/ext-mongo.ini,
/usr/local/etc/php/5.6/conf.d/ext-opcache.ini,
/usr/local/etc/php/5.6/conf.d/ext-redis.ini,
/usr/local/etc/php/5.6/conf.d/ext-tidy.ini,
/usr/local/etc/php/5.6/conf.d/ext-twig.ini,
/usr/local/etc/php/5.6/conf.d/ext-xdebug.ini,
/usr/local/etc/php/5.6/conf.d/ext-yaml.ini
```

**Comment by bocharsky-bw** [comment]
For me it's:
```
Configuration File (php.ini) Path: /usr/local/etc/php/7.1
Loaded Configuration File:         /usr/local/etc/php/7.1/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.1/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.1/conf.d/ext-imagick.ini,
/usr/local/etc/php/7.1/conf.d/ext-intl.ini,
/usr/local/etc/php/7.1/conf.d/ext-mcrypt.ini,
/usr/local/etc/php/7.1/conf.d/ext-oauth.ini,
/usr/local/etc/php/7.1/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.1/conf.d/ext-pdo_pgsql.ini,
/usr/local/etc/php/7.1/conf.d/ext-xdebug.ini,
/usr/local/etc/php/7.1/conf.d/ext-yaml.ini
```

I also don't see any duplication there.

**Comment by javian** [comment]
How about the content in the files in `conf.d` is there any duplication there ?

**Comment by bocharsky-bw** [comment]
Each file in `conf.d` dir includes only its `.so` extension, everything looks fine there.

**Comment by bocharsky-bw** [comment]
Hey guys, I think I mislead you a bit... I investigated this a bit more, for me these errors occur when I run `composer install` on Symfony project, i.e. where composer run [Symfony scripts](https://github.com/symfony/symfony-demo/blob/master/composer.json#L39-L54). Here's a full output of `composer install`:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'yaml' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'OAuth' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'yaml' already loaded in Unknown on line 0
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'yaml' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'OAuth' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'yaml' already loaded in Unknown on line 0

 // Clearing the cache for the dev environment with debug
 // true


 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
PHP Warning:  Module 'intl' already loaded in Unknown on line 0
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'OAuth' already loaded in Unknown on line 0
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0
PHP Warning:  Module 'yaml' already loaded in Unknown on line 0

Warning: Module 'imagick' already loaded in Unknown on line 0

Warning: Module 'intl' already loaded in Unknown on line 0

Warning: Module 'mcrypt' already loaded in Unknown on line 0

Warning: Module 'OAuth' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'yaml' already loaded in Unknown on line 0

 Trying to install assets as relative symbolic links.

 --- ------------------------------ ------------------
      Bundle                         Method / Error
 --- ------------------------------ ------------------
  ✔   WhiteOctoberPagerfantaBundle   relative symlink
 --- ------------------------------ ------------------


 [OK] All assets were successfully installed.


> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

Does it clearer now?

**Comment by alcaeus** [comment]
Are you by any chance using composer 1.3.0 or later? In that case, please update `sensio/distribution-bundle`. Composer now forks itself to disable xdebug, which caused the DistributionBundle to load ini files multiple times. This was fixed in https://github.com/sensiolabs/SensioDistributionBundle/pull/304, which is included in 5.0.17.

**Comment by bocharsky-bw** [comment]
@alcaeus Ah, that's exactly my problem! Yes, I have the latest Composer `1.3.1`. Thanks, after upgrading `sensio/distribution-bundle` problem is gone 👍

**Comment by viperdigo** [comment]
My problem still not solving even with the updated composer and the sensio ...

**Comment by xmontero** [comment]
I got the same problem. I reached the very same point: Failed in the `symfony-scripts`. In particular it failed with the `executeBuildBootstrap` method of the `SensioDistributionBundle` when it launches a second `php` process the the line `$process->run(function ($type, $buffer) use ($event) { $event->getIO()->write($buffer, false); });`

For some reason the problem was originated because of an incoherent status of the `composer.lock file`. After a  `composer update` (and of course running all my unit-tests to ensure nothing was broken), the error was gone and the composer run was clean.

**Comment by jxsl13** [comment]
had the same problem
 ` $ php --ini
PHP Warning:  Module 'pdo_pgsql' already loaded in Unknown on line 0

Warning: Module 'pdo_pgsql' already loaded in Unknown on line 0
Configuration File (php.ini) Path: /usr/local/etc/php/7.1
Loaded Configuration File:         /usr/local/etc/php/7.1/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.1/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.1/conf.d/ext-intl.ini,
/usr/local/etc/php/7.1/conf.d/ext-pdo_pgsql.ini`

it is because the pdo-pgsql module is already build in the binary of php, so that you do not need to use a dynamic module (with the *.so extension)
What I did to get rid of the error was to comment out the first extension line within: /usr/local/etc/php/7.1/conf.d/ext-pdo_pgsql.ini`
hopefully this helps someone.

**Comment by javian** [comment]
@jxsl13 that should only happen if you installed php with `--with-postgres`

**Comment by Voyager-One** [comment]
@jxsl13 that fixed! thank you :)

**Comment by honestxll** [comment]
@jxsl13 very useful！thanks :)

**Comment by javian** [comment]
Locking issue. If you are having problems related to this please open a new issue. Thanks!
