### ISSUE TITLE
PHP55-imagick appears to be broken

### ISSUE THREAD

**Issue by meljturner** [Homebrew/homebrew-php#3912]
## Description

PHP55-imagick appears to be broken

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       |10.12.2
**Homebrew Version:**   |Homebrew 1.1.7
Homebrew/homebrew-core (git revision 9ac50; last commit 2017-01-13)
**PHP Version in use:** | 5.5.38
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**
iMac:element-test mel$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
iMac:element-test mel$ 

**Output of php -v:**
iMac:element-test mel$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-imagick/imagick.so' - dlopen(/usr/local/opt/php55-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php55-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php55-imagick/imagick.so' - dlopen(/usr/local/opt/php55-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php55-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 5.5.38 (cli) (built: Jan 13 2017 09:42:23) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
iMac:element-test mel$ 

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

**Comment by javian** [comment]
#3913 should resolve any imagick issues once merged.

**Comment by meljturner** [comment]
It didn't fix it for me. Even after reinstalling everything.

**Comment by javian** [comment]
@meljturner it has not been merged yet. The issue is that the php-imagick version for 5 is no up to date and can't compile against the current php source.

**Comment by ilovezfs** [comment]
@meljturner @javian Just a heads up that we've now merged ImageMagick 6 as "imagemagick@6"

**Comment by meljturner** [comment]
Thanks for the notification.
I reinstalled php56 and php56-imagick and still receive the following message; any ideas?

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0


Mel Turner

meljturner@burntlands.ca <mailto:meljturner@burntlands.ca>
160 Fairbairn Bros. St.
Almonte, Ont.
K0A 1A0
613-256-1946





On Jan 17, 2017, at 5:25 AM, ilovezfs <notifications@github.com> wrote:

@meljturner <https://github.com/meljturner> @javian <https://github.com/javian> Just a heads up that we've now merged ImageMagick 6 as "imagemagick@6"

**Comment by fdelaiglesia-mobaloo** [comment]
I managed to fix the issue. It is not the best approach but had to solve the issue fast as bug showed up in middle of development when updating other libraries via brew.

As far as I understand what happens is that when imagemagick@7 is installed/updated links on the /usr/local/opt from previous versions are flushed, i suppose brew does this automatically.

After several tests, reinstall and googling found out that imagemagick@6 stills there but not referenced so i did the link manually:

ln /usr/local/Cellar/imagemagick/6.9.7-0/lib/* /usr/local/opt/imagemagick/lib/

restart apache and working again.

**Comment by meljturner** [comment]
The fix using brew seems to be:
brew unlink imagemagick
brew install imagmagick@6   (keg only)
brew link imagemagick@6 —force

then restart php and apache
