### ISSUE TITLE
why build phpxx-opcache will need to download another source package instead of use already downloaded php source?

### ISSUE THREAD

**Issue by steve3d** [Homebrew/homebrew-php#4641]
## Description

I'm using a thread-safe version of php in my dev environment, and with opcache ext, and every time php need update, I need to also rebuild the opcache extension.

for example, with version 7.1.12, the php71 need to download the php source, and downloaded file was renamed to `php71-7.1.12`, and for php71-opcache, it still need to download same php7.1.12 source but this time it was renamed as `php71-opcache-7.1.12`. both `php71-7.1.12` `php71-opcache-7.1.12` are exact same source package, why need to download another instead of just using the source from `php71`?

and I believe this also exists with `php71-intl` `php71-pspell` and all the extensions from php source package. this is a huge joke, in order to get all these bundled extension from a source build, one need to download php source package dozen times?

the same problem also exists with **any** php version 

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | _10.13.1_
**Homebrew version:**   | _Homebrew 1.3.9_
**PHP version in use:** | _not relevant _
**Xcode version:**      | _not relevant_

**Comment by SMillerDev** [comment]
This is mostly a matter of how formulas work. While the opcache formula shares some parts with the php formula itself, in the end its still a different formula and the source will be a different download. This would only be solved by bundling all formula that depend on a single php source version into a single php formula which also builds all extensions.

**Comment by steve3d** [comment]
well, but I still don't understand, why is there someone want to use php-7.1.10 and use opcache with version 7.1.6, I believe any one want php and its' bundled extension be installed with same version. if they are all same, they can try to use the same source package as php's, so there is no need to download dozen times of exact same source package.

**Comment by SMillerDev** [comment]
It's not about allowing different sources for PHP dependencies. It's about keeping the source for a different formula separate from the other formula sources. This is the way Homebrew formulae are set up, it isn't specific to PHP in any way. You could hack around it but that just seems like a waste of time to me.

**Comment by steve3d** [comment]
ah, I think you just mixed my idea, I'm talking about the source package, like files from here: 
 `http://php.net/get/php-7.2.0.tar.gz/from/a/mirror` not the prebuilt sources.

they all come from a same source package for php7.2, if we build these extensions from source, they all need to download the `php-7.2.0.tar.gz` file from the url above,  and I don't think this have anything to with the dependencies, as I come from China, download 20 times of this file will be a huge pain for our country's special `internet`. and I believe there a some countries like mine.

I'm just asking if there is a possibility to use the exact same `php-7.2.0.tar.gz` downloaded from `http://php.net/get/php-7.2.0.tar.gz/from/a/mirror` instead of download this file dozens of times and rename it each time. 

and this is a exact same file, and I can not understand why this is related to  PHP dependencies.

**Comment by SMillerDev** [comment]
The way homebrew works is that it saves the formula source file as `<Formula name>-<version>.<file extension>` in `~/Library/Caches/Homebrew/Formula`. It then uses that source to build the formula. This means that for the formula the php source is `php72-7.2.0.tar.gz` and the php imagick source is `php72-imagick-1.3.0.tar.gz` or something like that. I guess you could work around this by downloading the file once and copying it to to the different filenames it would need. But this is just how homebrew does source management.

**Comment by steve3d** [comment]
well then, I believe this bug should be with homebrew instead of here.
