### ISSUE TITLE
Warning: Calling 'depends_on :postgresql' is deprecated!

### ISSUE THREAD

**Issue by kenorb** [Homebrew/homebrew-php#4720]
## Description

```
Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:56:in `init'
Please report this to the homebrew/php tap!
Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:56:in `init'
Please report this to the homebrew/php tap!
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       |_10.12.6_
**Homebrew version:**   | _1.4.3-75-g02e4cae_
**PHP version in use:** | _7.1.7_
**Xcode version:**      | _8.3_
**Ruby version:**      | _ruby 2.5.0p0 (2017-12-25 revision 61468)_

**Comment by javian** [comment]
The formulas should have all been changed already and if you run `brew update` it ought to fix it (you seem to not be running the latest version?).

**Comment by kenorb** [comment]
Same in Homebrew 1.5.0-6-gd14fd49 (after `brew update`). How do I update `homebrew-php` tap?

**Comment by SMillerDev** [comment]
that would happen through `brew update`

**Comment by SMillerDev** [comment]
Is this fixed now?

**Comment by kenorb** [comment]
Still showing, as mentioned, `brew update` didn't update `homebrew-php` for some reason. Is there another command to update `homebrew-php` tap specifically?

**Comment by SMillerDev** [comment]
what does `git -C $(brew --repo homebrew/php) fetch -v` show?

**Comment by kenorb** [comment]
```
$ git -C $(brew --repo homebrew/php) fetch -v
POST git-upload-pack (727 bytes)
remote: Counting objects: 25, done.
remote: Total 25 (delta 15), reused 15 (delta 15), pack-reused 10
Unpacking objects: 100% (25/25), done.
From https://github.com/Homebrew/homebrew-php
 * [new branch]        70opcacherev3                -> origin/70opcacherev3
 * [new branch]        apxsdetectionfix             -> origin/apxsdetectionfix
 * [new branch]        drupal-code-sniffer-8.x-2.12 -> origin/drupal-code-sniffer-8.x-2.12
 * [new branch]        drush-8.1.12                 -> origin/drush-8.1.12
 * [new branch]        javian-patch-2               -> origin/javian-patch-2
 * [new branch]        javian-patch-3               -> origin/javian-patch-3
 * [new branch]        javian-patch-4               -> origin/javian-patch-4
 * [new branch]        javian-patch-5               -> origin/javian-patch-5
 * [new branch]        libmustache-0.4.3            -> origin/libmustache-0.4.3
 = [up to date]        master                       -> origin/master
 * [new branch]        phan-0.9.3                   -> origin/phan-0.9.3

$ brew update
Updated Homebrew from d558ec093 to 91f980208.
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
binutils ✔         btfs               dhall-json         groonga            nano               ucon64
lame ✔             calc               dpkg               gsoap              ncdu               udunits
ncurses ✔          ccache             encfs              ice                netcdf             userspace-rcu
rsync ✔            cfr-decompiler     fizmo              igv                openrtsp           vault
youtube-dl ✔       checkstyle         folly              joplin             osquery            wiredtiger
argyll-cms         clamav             fox                lbdb               pcb
armadillo          davmail            freeradius-server  libebur128         ranger
bit                dep                gitbucket          magic-wormhole     rgbds
bork               dependency-check   gjs                mutt               tintin
Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:56:in `init'
Please report this to the homebrew/php tap!

Warning: Calling Requirement.default_formula is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Requirements/php-meta-requirement.rb:19:in `<class:PhpMetaRequirement>'
Please report this to the homebrew/php tap!

Error: Calling BottleSpecification.revision is disabled!
Use BottleSpecification.rebuild instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/php56-xhprof.rb:14:in `block in <class:Php56Xhprof>'
Please report this to the homebrew/php tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-php/issues

$ brew update
Already up-to-date.

$ brew --prefix homebrew/php/php71
Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:56:in `init'
Please report this to the homebrew/php tap!

/usr/local/opt/php71
```

So same issue.

**Comment by kenorb** [comment]
Ok, works now, I had to switch to `master` branch, for some reason it was on different one.

```
$ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php
$ git checkout master -f
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ git reset origin/master --hard
HEAD is now at db73f2d6 chore: remove unmaintained php-install formula
$ brew --prefix homebrew/php/php71
/usr/local/opt/php71
```

Thanks.
